version: '3.8'

networks:
  natsgen-net:
    name: natsgen-net
  

services:
  nats:
    image: bitnami/nats:2
    command: ["nats-server", "--jetstream"]
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    volumes:
      - nats-data:/opt/bitnami/nats
    networks:
      - natsgen-net

volumes:
  nats-data: {}
