version: '3.8'

networks:
  natsgen-net:
    name: natsgen-net
    external: true

services:
  nats-box:
    image: natsio/nats-box:latest
    command: [sleep, 1d]
    environment:
      NATS_URL: nats://nats:4222
    networks:
      - natsgen-net

